### ISSUE TITLE
Memory chip: remove degree 4 constraint

### ISSUE THREAD

**Issue by morganthomas** [valida-xyz/valida#77]
A comment in `memory/src/stark.rs` says `FIXME: Degree constraint 4, need to remove`. It’s not clear to me why a degree 4 constraint needs to be removed. Is this an optimization or a requirement for functional completeness and correctness?

**Comment by 0xKanekiKen** [comment]
I don't recall where I saw it but I think plonky3 could only support a max degree of 3, maybe that's reason. I could be wrong though.

**Comment by dlubarov** [comment]
We've been targeting a degree bound 3, at least for the CPU AIR. It's not a hard requirement - Plonky3 should work with higher degrees - but having degree <= 3 constraints means we can compute the quotient polynomial by evaluating it at `2n` points (not `3n` since division by the zerofier reduces degree by `n`).

As part of that, we compute LDEs of each trace polynomial with a blowup factor of 2. If we used degree 4 constraints, our prover code would end up doing LDEs with a 4x blowup, roughly doubling its cost.
